Fri, 10 Jul 2015 22:49:13 web.py[line:1357] ERROR Uncaught exception GET / (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Cookie': '_ga=GA1.1.228519919.1435468354; username="2|1:0|10:1435475956|8:username|24:6ams5YWL5omO5YWL5Lyv5qC8|2a906efa34b37ca5b2205a33162f8ff92fb8a9105520f7f98dd4d3f76959d34d"', 'Host': 'localhost:8080', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12'})
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1270, in _when_complete
    callback()
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1291, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 90, in get
    homeBase.init(self)
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 43, in init
    self.signedid = self.user.uid
AttributeError: 'NoneType' object has no attribute 'uid'
Fri, 10 Jul 2015 22:49:13 web.py[line:1780] ERROR 500 GET / (127.0.0.1) 151.69ms
Fri, 10 Jul 2015 22:49:14 web.py[line:1357] ERROR Uncaught exception GET / (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Cookie': '_ga=GA1.1.228519919.1435468354; username="2|1:0|10:1435475956|8:username|24:6ams5YWL5omO5YWL5Lyv5qC8|2a906efa34b37ca5b2205a33162f8ff92fb8a9105520f7f98dd4d3f76959d34d"', 'Host': 'localhost:8080', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12'})
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1270, in _when_complete
    callback()
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1291, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 90, in get
    homeBase.init(self)
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 43, in init
    self.signedid = self.user.uid
AttributeError: 'NoneType' object has no attribute 'uid'
Fri, 10 Jul 2015 22:49:14 web.py[line:1780] ERROR 500 GET / (127.0.0.1) 16.22ms
Fri, 10 Jul 2015 22:49:17 web.py[line:1357] ERROR Uncaught exception GET / (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Cookie': '_ga=GA1.1.228519919.1435468354; username="2|1:0|10:1435475956|8:username|24:6ams5YWL5omO5YWL5Lyv5qC8|2a906efa34b37ca5b2205a33162f8ff92fb8a9105520f7f98dd4d3f76959d34d"', 'Host': 'localhost:8080', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12'})
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1270, in _when_complete
    callback()
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1291, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 90, in get
    homeBase.init(self)
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 43, in init
    self.signedid = self.user.uid
AttributeError: 'NoneType' object has no attribute 'uid'
Fri, 10 Jul 2015 22:49:17 web.py[line:1780] ERROR 500 GET / (127.0.0.1) 12.74ms
Fri, 10 Jul 2015 22:50:59 web.py[line:1357] ERROR Uncaught exception GET / (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Cookie': '_ga=GA1.1.228519919.1435468354; username="2|1:0|10:1435475956|8:username|24:6ams5YWL5omO5YWL5Lyv5qC8|2a906efa34b37ca5b2205a33162f8ff92fb8a9105520f7f98dd4d3f76959d34d"', 'Host': 'localhost:8080', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12'})
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1270, in _when_complete
    callback()
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1291, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 90, in get
    homeBase.init(self)
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 43, in init
    self.signedid = self.user.uid
AttributeError: 'NoneType' object has no attribute 'uid'
Fri, 10 Jul 2015 22:50:59 web.py[line:1780] ERROR 500 GET / (127.0.0.1) 20.90ms
Fri, 10 Jul 2015 22:51:24 web.py[line:1357] ERROR Uncaught exception GET / (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Cookie': '_ga=GA1.1.228519919.1435468354; username="2|1:0|10:1435475956|8:username|24:6ams5YWL5omO5YWL5Lyv5qC8|2a906efa34b37ca5b2205a33162f8ff92fb8a9105520f7f98dd4d3f76959d34d"', 'Host': 'localhost:8080', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12'})
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1270, in _when_complete
    callback()
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1291, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 90, in get
    homeBase.init(self)
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 43, in init
    self.signedid = self.user.uid
AttributeError: 'NoneType' object has no attribute 'uid'
Fri, 10 Jul 2015 22:51:24 web.py[line:1780] ERROR 500 GET / (127.0.0.1) 25.45ms
Fri, 10 Jul 2015 22:51:30 web.py[line:1357] ERROR Uncaught exception GET / (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Cookie': '_ga=GA1.1.228519919.1435468354; username="2|1:0|10:1435475956|8:username|24:6ams5YWL5omO5YWL5Lyv5qC8|2a906efa34b37ca5b2205a33162f8ff92fb8a9105520f7f98dd4d3f76959d34d"', 'Host': 'localhost:8080', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12'})
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1270, in _when_complete
    callback()
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1291, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 90, in get
    homeBase.init(self)
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 43, in init
    self.signedid = self.user.uid
AttributeError: 'NoneType' object has no attribute 'uid'
Fri, 10 Jul 2015 22:51:30 web.py[line:1780] ERROR 500 GET / (127.0.0.1) 20.66ms
Fri, 10 Jul 2015 22:51:36 web.py[line:1357] ERROR Uncaught exception GET / (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Cookie': '_ga=GA1.1.228519919.1435468354; username="2|1:0|10:1435475956|8:username|24:6ams5YWL5omO5YWL5Lyv5qC8|2a906efa34b37ca5b2205a33162f8ff92fb8a9105520f7f98dd4d3f76959d34d"', 'Host': 'localhost:8080', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12'})
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1270, in _when_complete
    callback()
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1291, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 90, in get
    homeBase.init(self)
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 43, in init
    self.signedid = self.user.uid
AttributeError: 'NoneType' object has no attribute 'uid'
Fri, 10 Jul 2015 22:51:36 web.py[line:1780] ERROR 500 GET / (127.0.0.1) 4.36ms
Fri, 10 Jul 2015 22:52:57 web.py[line:1357] ERROR Uncaught exception GET / (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Cookie': '_ga=GA1.1.228519919.1435468354; username="2|1:0|10:1435475956|8:username|24:6ams5YWL5omO5YWL5Lyv5qC8|2a906efa34b37ca5b2205a33162f8ff92fb8a9105520f7f98dd4d3f76959d34d"', 'Host': 'localhost:8080', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12'})
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1270, in _when_complete
    callback()
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1291, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 90, in get
    homeBase.init(self)
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/home.py", line 43, in init
    self.signedid = self.user.uid
AttributeError: 'NoneType' object has no attribute 'uid'
Fri, 10 Jul 2015 22:52:57 web.py[line:1780] ERROR 500 GET / (127.0.0.1) 4.41ms
Fri, 10 Jul 2015 22:57:25 web.py[line:1357] ERROR Uncaught exception POST /signin (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8080', method='POST', uri='/signin', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://localhost:8080', 'Content-Length': '35', 'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8080', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12', 'Connection': 'keep-alive', 'Cookie': '_ga=GA1.1.228519919.1435468354; _gat=1', 'Referer': 'http://localhost:8080/signin', 'Content-Type': 'application/x-www-form-urlencoded'})
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1270, in _when_complete
    callback()
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1291, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/admin.py", line 55, in post
    user = self.session.query(User).filter(User.username==username).one()
  File "/Library/Python/2.7/site-packages/SQLAlchemy-0.9.7-py2.7-macosx-10.9-intel.egg/sqlalchemy/orm/query.py", line 2375, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
Fri, 10 Jul 2015 22:57:25 web.py[line:1780] ERROR 500 POST /signin (127.0.0.1) 24.18ms
Fri, 10 Jul 2015 22:58:39 web.py[line:1357] ERROR Uncaught exception POST /signin (127.0.0.1)
HTTPRequest(protocol='http', host='localhost:8080', method='POST', uri='/signin', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://localhost:8080', 'Content-Length': '28', 'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8080', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12', 'Connection': 'keep-alive', 'Cookie': '_ga=GA1.1.228519919.1435468354; _gat=1', 'Referer': 'http://localhost:8080/signin', 'Content-Type': 'application/x-www-form-urlencoded'})
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1270, in _when_complete
    callback()
  File "/Library/Python/2.7/site-packages/tornado-3.2.1-py2.7-macosx-10.9-intel.egg/tornado/web.py", line 1291, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/Users/cheesewong/PycharmProjects/simple/cms/handlers/admin.py", line 55, in post
    user = self.session.query(User).filter(User.username==username).one()
  File "/Library/Python/2.7/site-packages/SQLAlchemy-0.9.7-py2.7-macosx-10.9-intel.egg/sqlalchemy/orm/query.py", line 2375, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
Fri, 10 Jul 2015 22:58:40 web.py[line:1780] ERROR 500 POST /signin (127.0.0.1) 20.63ms
